name: Build Image

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up build dependencies
      run: |
        sudo apt-get update
        sudo xargs -a depends apt-get install -y

    - name: Export secret to config file
      run: echo "FIRST_USER_PASS=${{ secrets.PI_USER_PASSWORD }}" > config

    - name: Run build script
      run: |
        chmod +x ./build.sh
        sudo ./build.sh

    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: Raspberry-Pi-image
        path: "deploy/*.zip"
